[package]
name = "aleo"
version = "0.2.0"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "Aleo"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/aleo"
keywords = ["aleo", "cryptography", "blockchain", "decentralized", "zero-knowledge"]
categories = ["cryptography::cryptocurrencies", "operating-systems"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[workspace]
members = ["rust/account", "rust/environment", "rust/record", "wasm"]

[lib]
path = "cli/lib.rs"

[[bin]]
name = "aleo"
path = "cli/main.rs"

[dependencies.aleo-account]
path = "./rust/account"
version = "0.2.0"

[dependencies.aleo-record]
path = "./rust/record"
version = "0.2.0"

[dependencies.snarkos-storage]
version = "1.3.8"
default-features = false
features = ["mem_storage"]

[dependencies.snarkvm-algorithms]
version = "0.5.5"
features = ["wasm"]

[dependencies.snarkvm-dpc]
version = "0.6.0"

[dependencies.snarkvm-utilities]
version = "0.5.5"

[dependencies.anyhow]
version = "1.0.41"

[dependencies.base64]
version = "0.13"

[dependencies.colored]
version = "2"

[dependencies.hex]
version = "0.4.3"

[dependencies.rand]
version = "0.8"
default-features = false

[dependencies.rand_chacha]
version = "0.3.0"
default-features = false

[dependencies.reqwest]
version = "0.11"
features = ["json"]

[dependencies.self_update]
version = "0.27"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.serde_json]
version = "1.0"

[dependencies.structopt]
version = "0.3"

[dependencies.thiserror]
version = "1.0"

[dependencies.uuid]
version = "0.8.1"
features = ["v4", "serde"]

[dependencies.wasm-bindgen]
version = "0.2.74"

[dev-dependencies.colored]
version = "2"
features = ["no-color"]

[dev-dependencies.rusty-hook]
version = "0.11.2"

[dev-dependencies.tokio]
version = "1.7.0"
features = ["rt-multi-thread"]

[dev-dependencies.wasm-bindgen-test]
version = "0.3.23"

[dev-dependencies.wiremock]
version = "0.5"

[profile.release]
opt-level = 3
lto = "thin"
incremental = true

[profile.bench]
opt-level = 3
lto = "thin"
incremental = true
debug = false
debug-assertions = false
rpath = false

[profile.dev]
opt-level = 2
lto = "thin"
incremental = true

[profile.test]
opt-level = 2
lto = "thin"
incremental = true
debug = true
debug-assertions = true
