[package]
name = "aleo"
version = "0.2.0"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "Aleo"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/aleo"
keywords = ["aleo", "cryptography", "blockchain", "decentralized", "zero-knowledge"]
categories = ["cryptography::cryptocurrencies", "operating-systems"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

#[lib]
#crate-type = ["cdylib", "rlib"]

[[bench]]
name = "account"
path = "benches/account.rs"
harness = false

[dependencies]
#snarkvm-dpc = { version = "0.0.2", default-features = false }
#snarkvm-errors = { version = "0.0.2", default-features = false }
#snarkvm-models = { version = "0.0.2", default-features = false }
#snarkvm-objects = { version = "0.0.2", default-features = false }
#snarkvm-storage = { version = "0.0.2", default-features = false }
#snarkvm-utilities = { version = "0.0.2" }

snarkvm-dpc = { version = "0.0.2" }
snarkvm-errors = { version = "0.0.2" }
snarkvm-models = { version = "0.0.2" }
snarkvm-objects = { version = "0.0.2" }
snarkvm-storage = { version = "0.0.2" }
snarkvm-utilities = { version = "0.0.2" }

anyhow = { version = "1.0.38" }
colored = { version = "2" }
hex = { version = "0.4.2" }
rand = { version = "0.7", default-features = false, features = ["wasm-bindgen"] }
rand_chacha = { version = "0.2", default-features = false }
self_update = { version = "0.23" }
structopt = { version = "0.3" }
thiserror = { version = "1.0" }
wasm-bindgen = { version = "0.2.70" }

[dev-dependencies]
colored = { version = "2", features = ["no-color"] }
criterion = { version = "0.3.1" }
rusty-hook = { version = "0.11.2" }
wasm-bindgen-test = { version = "0.3.20" }

[profile.release]
opt-level = 3
lto = "thin"
incremental = true

[profile.bench]
opt-level = 3
lto = "thin"
incremental = true
debug = false
debug-assertions = false
rpath = false

[profile.dev]
opt-level = 2
lto = "thin"
incremental = true

[profile.test]
opt-level = 2
lto = "thin"
incremental = true
debug = true
debug-assertions = false
