[package]
name = "aleo"
version = "0.2.0"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "Aleo"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/aleo"
keywords = ["aleo", "cryptography", "blockchain", "decentralized", "zero-knowledge"]
categories = ["cryptography::cryptocurrencies", "operating-systems"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[workspace]
members = ["account", "wasm"]

[dependencies]
#snarkvm-dpc = { version = "0.0.2", default-features = false }
#snarkvm-errors = { version = "0.0.2", default-features = false }
#snarkvm-models = { version = "0.0.2", default-features = false }
#snarkvm-objects = { version = "0.0.2", default-features = false }
#snarkvm-storage = { version = "0.0.2", default-features = false, optional = true }
#snarkvm-utilities = { version = "0.0.2", default-features = false }

aleo-account = { path = "./account", version = "0.2.0" }

snarkvm-dpc = { version = "0.0.2" }
snarkvm-errors = { version = "0.0.2" }
snarkvm-models = { version = "0.0.2" }
snarkvm-objects = { version = "0.0.2" }
snarkvm-storage = { version = "0.0.2" }
snarkvm-utilities = { version = "0.0.2" }

anyhow = { version = "1.0.38" }
base64 = { version = "0.13" }
colored = { version = "2" }
hex = { version = "0.4.2" }
rand = { version = "0.7", default-features = false, features = ["wasm-bindgen"] }
rand_chacha = { version = "0.2", default-features = false }
reqwest = { version = "0.11", features = ["json"] }
self_update = { version = "0.23" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
structopt = { version = "0.3" }
thiserror = { version = "1.0" }
uuid = { version = "0.8.1", features = ["v4", "serde"] }
wasm-bindgen = { version = "0.2.70" }

[dev-dependencies]
colored = { version = "2", features = ["no-color"] }
wiremock = { version = "0.4" }
rusty-hook = { version = "0.11.2" }
wasm-bindgen-test = { version = "0.3.20" }
tokio = { version = "1.1.0", features = ["rt-multi-thread"] }

[profile.release]
opt-level = 3
lto = "thin"
incremental = true

[profile.bench]
opt-level = 3
lto = "thin"
incremental = true
debug = false
debug-assertions = false
rpath = false

[profile.dev]
opt-level = 2
lto = "thin"
incremental = true

[profile.test]
opt-level = 2
lto = "thin"
incremental = true
debug = true
debug-assertions = true
